CREATE DATABASE SLAES_PROJECT

SELECT *
FROM SLAES_PROJECT.DBO.sales_data_sample

SELECT COUNT(DISTINCT(COUNTRY))
FROM SLAES_PROJECT.DBO.sales_data_sample

--IT WAS FOUND OUT THAT THE COMPANY IS SENDING ORDER IN 19 DIFFERENT COUNTRIES

SELECT DISTINCT(STATUS)
FROM SLAES_PROJECT.DBO.sales_data_sample


SELECT COUNT(DISTINCT(STATUS))
FROM SLAES_PROJECT.DBO.sales_data_sample

--IT WAS FOUND OUT THAT THERE WERE 6 DIFFERENT TYPES OF ORDER STATUSES Resolved, On Hold, Cancelled, Shipped, Disputed, In Process 

SELECT COUNT(DISTINCT(PRODUCTLINE))
FROM SLAES_PROJECT.DBO.sales_data_sample

--IT WAS FOUND OUT THAT THERE WERE 7 DIFFERENT TYPES OF PRODUCTS 


SELECT COUNT(DISTINCT(CUSTOMERNAME))
FROM SLAES_PROJECT.DBO.sales_data_sample

--IT WAS FOUND OUT THAT THERE WERE 92 DIFFERENT CUSTOMERS

--DATA EXPLORATORY ANALYSIS

--1. FINDING OUT THE PRODUCT OF HIGHEST SALES

SELECT PRODUCTLINE, SUM(SALES) TOTAL_SALES
FROM SLAES_PROJECT.DBO.sales_data_sample
GROUP BY PRODUCTLINE
ORDER BY 2 DESC

--2. FINDING OUT THE BEST YEAR OF SALES

SELECT YEAR_ID, SUM(SALES) REVENUE
FROM SLAES_PROJECT.DBO.sales_data_sample
GROUP BY YEAR_ID
ORDER BY REVENUE DESC 

--3. FURTHER ANALYSIS WAS DONE IN ORDER TO FIND OUT WHY 2005 HAVE LEAST SALES

SELECT MONTH_ID
FROM SLAES_PROJECT.DBO.sales_data_sample
WHERE YEAR_ID = 2004
GROUP BY MONTH_ID

SELECT MONTH_ID
FROM SLAES_PROJECT.DBO.sales_data_sample
WHERE YEAR_ID = 2003
GROUP BY MONTH_ID

SELECT MONTH_ID
FROM SLAES_PROJECT.DBO.sales_data_sample
WHERE YEAR_ID = 2005
GROUP BY MONTH_ID

--IT WAS FOUND OUT THAT 2005 HAD THE LEAST SALES BECAUSE SALES TOOK PLACE FOR ONLY 5 MONTHS 

--4. WHICH MONTH HAS THE BEST SALES 

SELECT MONTH_ID, SUM(SALES) REVENUE, COUNT(ORDERLINENUMBER) FREQUENCY
FROM SLAES_PROJECT.DBO.sales_data_sample
WHERE YEAR_ID = 2004
GROUP BY MONTH_ID
ORDER BY REVENUE DESC

SELECT MONTH_ID, SUM(SALES) REVENUE, COUNT(ORDERLINENUMBER) FREQUENCY
FROM SLAES_PROJECT.DBO.sales_data_sample
WHERE YEAR_ID = 2005
GROUP BY MONTH_ID
ORDER BY REVENUE DESC

SELECT MONTH_ID, SUM(SALES) REVENUE, COUNT(ORDERLINENUMBER) FREQUENCY
FROM SLAES_PROJECT.DBO.sales_data_sample
WHERE YEAR_ID = 2003
GROUP BY MONTH_ID
ORDER BY REVENUE DESC


--5. WHICH COUNTRY HAD THE MOST SALES


SELECT COUNTRY, SUM(SALES) REVENUE
FROM SLAES_PROJECT.DBO.sales_data_sample
GROUP BY COUNTRY
ORDER BY REVENUE DESC

--6. WHO IS THE BEST CUSTOMER

SELECT CUSTOMERNAME, SUM(QUANTITYORDERED) AS ABC
FROM SLAES_PROJECT.DBO.sales_data_sample
GROUP BY CUSTOMERNAME
ORDER BY ABC DESC

--7. FURTHER ANALYSIS WAS DONE TO FIND OUT THE STATUS OF THE CUSTOMERS

SELECT CUSTOMERNAME, COUNT(QUANTITYORDERED) AS ABC,
CASE WHEN COUNT(QUANTITYORDERED) > AVG(QUANTITYORDERED) THEN 'LOYAL'
ELSE 'CHURNED'
END CUNSTOMETR_STATUS
FROM SLAES_PROJECT.DBO.sales_data_sample
GROUP BY CUSTOMERNAME
ORDER BY ABC DESC